name: cellbro
channels:
  - conda-forge
  - bioconda
dependencies:
  - python=3.8
  - flask
  - tqdm
  - scanpy
  - scvi-tools
  - leidenalg
  - trimap
  - psutil
  - plotly
  - dash
  - dash-bootstrap-components