name: cellbro
channels:
  - conda-forge
dependencies:
  - python=3.8
  - flask
  - tqdm
  - scanpy
  - scvi-tools
  - leidenalg
  - trimap
  - psutil
  - plotly
  - bioconda::gseapy
  - dash
  - dash-bootstrap-components
  - pip

# `conda env create -f environment.yml`
# `conda activate cellbro`
# `pip install -e ./scout` ### -e for development mode
# `pip install -e .` ####  -e for development mode