[build-system]
requires = ["setuptools>=70.1", "wheel>=0.43"]
build-backend = "setuptools.build_meta"

[project]
name = "cellbro-server"
version = "0.1"
description = "Backend server for CellBro"
authors = [
    { name = "lutrarutra", email = "lutrarutra@pm.me" }
]
requires-python = ">=3.11"

dependencies = [
    "numpy>= 2.2",
    "pandas>= 2.3",
    "loguru >= 0.7",
    "psycopg[binary,pool] >= 3.2",
    "SQLAlchemy >= 2.0",
    "pytz",
    "tzlocal",
    "uuid7",
    "fastapi",
    "uvicorn[standard]",
    "pydantic[email]",
    "python-multipart",
    "pydantic-settings",
    "passlib[argon2]",
    "pyjwt",
    "greenlet",
    "redis",
    "jinja2",
    "uuid6",
    "markdown",
    "jinjax",
    "websockets",
]

[tool.setuptools.packages.find]
where = ["."]
include = ["cellbro_server*"]

[tool.flake8]
max-line-length = 88
exclude = [
    ".git",
    "__pycache__",
]
extend-ignore = ["E501", "W292", "W293"]

